### ISSUE TITLE
field "data_stores" has wrong structure

### ISSUE THREAD

**Issue by marcusschroeder** [loadimpact/loadimpact-sdk-python#3]
Hi guys,

I might have discovered a small inconsistency within the Load Impact API. When updating a UserScenario it expects the field "data_stores" to be a json array of integers, but returns an array of objects on get requests.

### Example:
When I fetch my user scenario from the api and want to update the load_script
```
user_scenario = UserScenario.get(client, USER_SCENARIO_ID)
user_scenario.load_script = "fancy script"
user_scenario.update()
```
I get the following validation error:
```
{"message":"Validation failed","errors":{"data_stores":"data stores needs to be a list with \\"id\\" integers"}}
``` 

So I checked the payload delivered by loadimpact and found that the field data_stores is not an array of integers:
```
{'created': datetime.datetime(2014, 6, 18, 13, 41, 46, tzinfo=<loadimpact.utils.UTC object at 0x109fc7c10>),
 'data_stores': [{u'id': 1003310}],
 'id': 1755045,
 'load_script': u'fancy script',
 'name': u'fancy-name',
 'script_type': 'lua',
 'updated': datetime.datetime(2014, 6, 20, 15, 26, 58, tzinfo=<loadimpact.utils.UTC object at 0x109fe5950>)}
```

Now, when I reset the data-store before the update, it works:
```
user_scenario = UserScenario.get(client, USER_SCENARIO_ID)
user_scenario.load_script = "fancy script"
user_scenario.data_stores = [DATA_STORE_ID]
user_scenario.update()
```

Kind regards,
Marcus

**Comment by robingustafsson** [comment]
Hi Marcus.

I'm sorry, this may be the slowest reply and time-to-fix ever, but this issue has now been fixed in the SDK and a new version has been uploaded to PyPI.

The v2 API has not and will not be updated since it's being phased out. We now have a v3 API that we use for the new version of Load Impact and that we'll use in a future version of this SDK.

Thank you very much for reporting this issue. Again, my apologies for the very late response.

Kind regards,
Robin
